### ISSUE TITLE
Terraform crash when using `sumologic_policies`

### ISSUE THREAD

**Issue by mccartney** [SumoLogic/terraform-provider-sumologic#272]
## Steps to reproduce

`terraform apply` on this:
```
resource "sumologic_policies" "singleton" {
  audit = true
}
```

## Observed
```
│ Error: Plugin did not respond
│ 
│   with module.org-configuration[0].sumologic_policies.singleton,
│   on shared/org-configuration/main.tf line 1, in resource "sumologic_policies" "singleton":
│    1: resource "sumologic_policies" "singleton" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-sumologic_v2.9.10 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 99 [running]:
github.com/SumoLogic/terraform-provider-sumologic/sumologic.getUserConcurrentSessionsLimitPolicy(0xc000452cb0, 0x1caa7c8, 0x25)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_policies.go:151 +0x18d
github.com/SumoLogic/terraform-provider-sumologic/sumologic.resourceToPolicies(0xc000452cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_policies.go:135 +0x1b4
github.com/SumoLogic/terraform-provider-sumologic/sumologic.resourceSumologicPoliciesUpdate(0xc000452cb0, 0x1c7f780, 0xc000661310, 0x24, 0x2472220)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_policies.go:107 +0x45
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0002e9b80, 0xc000480f00, 0xc00063a3e0, 0x1c7f780, 0xc000661310, 0x1b51b01, 0xc0000cbe38, 0xc00018ed20)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:326 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000049000, 0xc0006f1a38, 0xc000480f00, 0xc00063a3e0, 0xc0001921a8, 0xc0007b4f80, 0x1b53b40)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0006501e0, 0x1e74630, 0xc0000fb350, 0xc0002cfce0, 0xc0006501e0, 0xc0000fb350, 0xc0007b1ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c46d20, 0xc0006501e0, 0x1e74630, 0xc0000fb350, 0xc0000a25a0, 0x0, 0x1e74630, 0xc0000fb350, 0xc0000d66c0, 0x22a)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000387a40, 0x1e7ddd8, 0xc000643680, 0xc00011d440, 0xc000484a80, 0x2430ba0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000387a40, 0x1e7ddd8, 0xc000643680, 0xc00011d440, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00058e1a0, 0xc000387a40, 0x1e7ddd8, 0xc000643680, 0xc00011d440)
        google.golang.org/grpc@v1.39.0/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd

Error: The terraform-provider-sumologic_v2.9.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mccartney** [comment]
Adding extra:
```
  user_concurrent_sessions_limit {
    enabled = false
    max_concurrent_sessions = 100
  }
```
helps

**Comment by emichaeli** [comment]
Thanks for reporting this @mccartney, this won't be a problem anymore after the changes implemented here: https://github.com/SumoLogic/terraform-provider-sumologic/pull/279
