### ISSUE TITLE
Error while getting role

### ISSUE THREAD

**Issue by SamuYoung-Factor-y** [SumoLogic/terraform-provider-sumologic#313]
While trying to getting an existing role name for use it for a new user this happened

```goroutine 52 [running]:
github.com/SumoLogic/terraform-provider-sumologic/sumologic.(*Client).GetRoleName(0xc000c48120, 0xc000c3e2f4, 0xa, 0xf39fe0, 0xc0007afc30, 0xc000062c01)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/data_source_sumologic_role.go:101 +0x2d2
github.com/SumoLogic/terraform-provider-sumologic/sumologic.dataSourceSumologicRoleRead(0xc000c525b0, 0x10b2de0, 0xc000c48120, 0xc000c525b0, 0x0)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/data_source_sumologic_role.go:61 +0x625
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000231ea0, 0xc00007e580, 0x10b2de0, 0xc000c48120, 0xc00012b9d8, 0x1, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:413 +0x91
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000177000, 0xc000c5daf8, 0xc00007e580, 0xc00007e580, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:451 +0x8f
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00065e2c8, 0x12ac510, 0xc000c3d590, 0xc00089adc0, 0xc00065e2c8, 0xc000c3d590, 0xc0004c0ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:1046 +0x42d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1079140, 0xc00065e2c8, 0x12ac510, 0xc000c3d590, 0xc000c48420, 0x0, 0x12ac510, 0xc000c3d590, 0xc000040540, 0x56)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000032a80, 0x12b5b18, 0xc000682600, 0xc00067d560, 0xc0004a4c90, 0x1876a50, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000032a80, 0x12b5b18, 0xc000682600, 0xc00067d560, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00036e3a0, 0xc000032a80, 0x12b5b18, 0xc000682600, 0xc00067d560)
        google.golang.org/grpc@v1.39.0/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd

Error: The terraform-provider-sumologic_v2.11.2 plugin crashed!```

**Comment by emichaeli** [comment]
Hey @SamuYoung-Factor-y, thanks for reporting this issue. I believe the most likely reason for your crash was that the role name provided was not found (e.g. due to a typo). We were not handling this case properly which is why the provider crashed. This is now fixed in https://github.com/SumoLogic/terraform-provider-sumologic/pull/316. Please upgrade to the newest provider version (`v.2.11.3`) and you should now at least receive a proper error message as opposed to the provider crashing. Thanks!
