### ISSUE TITLE
Terraform crash in logRequestAndResponse

### ISSUE THREAD

**Issue by mccartney** [SumoLogic/terraform-provider-sumologic#505]
Happened once for me:
```
│ Error: Request cancelled
│ 
│   with module.personal[0].sumologic_folder.personal,
│   on shared/personal/main.tf line 4, in resource "sumologic_folder" "personal":
│    4: resource "sumologic_folder" "personal" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-sumologic_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1908379]

goroutine 84 [running]:
github.com/SumoLogic/terraform-provider-sumologic/sumologic.logRequestAndResponse(0xc0007c6000, 0x0)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/sumologic_client.go:67 +0x159
github.com/SumoLogic/terraform-provider-sumologic/sumologic.(*Client).GetWithErrOpt(0xc000d90420, {0xc0007be720, 0xc000175970}, 0x0)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/sumologic_client.go:272 +0x233
github.com/SumoLogic/terraform-provider-sumologic/sumologic.(*Client).Get(...)
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/sumologic_client.go:254
github.com/SumoLogic/terraform-provider-sumologic/sumologic.(*Client).GetFolder(0x1b34705, {0xc00030c5c0, 0xc0001759e0})
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/sumologic_folder.go:13 +0x78
github.com/SumoLogic/terraform-provider-sumologic/sumologic.resourceSumologicFolderRead(0xc00052e8c0, {0x1b0ea20, 0xc000d90420})
        github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_folder.go:47 +0x15d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0007f0aa0, 0xc000b03180, {0x1b0ea20, 0xc000d90420})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0001ac758, {0xc000892480, 0x108dea6}, 0xc000892480)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1ae1040, 0xc0001ac758}, {0x1d18f50, 0xc000911890}, 0xc000892420, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a5c00, {0x1d291c8, 0xc00093a000}, 0xc000177440, 0xc000698840, 0x238a370, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0003a5c00, {0x1d291c8, 0xc00093a000}, 0xc000177440, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.0/server.go:938 +0x294

Error: The terraform-provider-sumologic_v2.21.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mflis-sumo** [comment]
This should be fixed by: https://github.com/SumoLogic/terraform-provider-sumologic/pull/496 but it's not available in any released/tagged version yet.
