### ISSUE TITLE
Crash in resource_sumologic_monitors_library_monitor.go:1552

### ISSUE THREAD

**Issue by mccartney** [SumoLogic/terraform-provider-sumologic#584]
Our CI build has observed this failure several times:
1. First, there are a lot of
```
Error: Request cancelled
[...]
The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```
2. And eventually the provider crashes:
```
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-sumologic_v2.27.0 plugin:

panic: interface conversion: interface {} is nil, not string

 goroutine 412 [running]:
 github.com/SumoLogic/terraform-provider-sumologic/sumologic.resourceToMonitorsLibraryMonitor(_)
 	github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_monitors_library_monitor.go:1552 +0xc45
 github.com/SumoLogic/terraform-provider-sumologic/sumologic.resourceSumologicMonitorsLibraryMonitorCreate(0xc000a07f10, {0xf2fb20, 0xc000b4e3c0})
 	github.com/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_monitors_library_monitor.go:736 +0x10f
 github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00094af00, 0xc00080fa90, 0xc0009e5100, {0xf2fb20, 0xc000b4e3c0})
 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
 github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000916000, 0xc000d45a68, 0xf3e710, 0xf)
 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
 github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e2e8, {0xc000a065b0, 0x48f946}, 0xc000a065b0)
 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
 github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xf01460, 0xc00000e2e8}, {0x113e230, 0xc0003bf170}, 0xc000d0e960, 0x0)
 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032dc00, {0x114e648, 0xc000184a80}, 0xc0004f8000, 0xc000628420, 0x17b62c0, 0x0)
 	google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
 google.golang.org/grpc.(*Server).handleStream(0xc00032dc00, {0x114e648, 0xc000184a80}, 0xc0004f8000, 0x0)
 	google.golang.org/grpc@v1.39.0/server.go:1617 +0xa2a
 google.golang.org/grpc.(*Server).serveStreams.func1.2()
 	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
 created by google.golang.org/grpc.(*Server).serveStreams.func1
 	google.golang.org/grpc@v1.39.0/server.go:938 +0x294

 Error: The terraform-provider-sumologic_v2.27.0 plugin crashed!

 This is always indicative of a bug within the plugin. It would be immensely
 helpful if you could report the crash with the plugin's maintainers so that it
 can be fixed. The output above should help diagnose the issue.
```

We are running
```
Terraform v1.5.4
on linux_amd64
```
if that matters

**Comment by dlinsumo** [comment]
Internal Sumo ticket SUMO-231263
